[package]
name = "elk"
description = "Executable & Linker Kit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
delf = { version = "0.1.0", path = "../delf" }
mmap = "0.1"
region = "2"
