[package]
name = "delf"
description = "demystify ELF"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-try-from-primitive = "1"
derive_more = "0.99"
nom = "5"
